"use client";

import { useEffect, useMemo, useState } from "react";

type SearchItem = { id:string; type:"Canone"|"Fonte italiana"|"Materia"; title:string; subtitle:string; text:string; terms:string[]; canon?:number; status:string };
type Theme = "light"|"dark";
type FontSize = "normal"|"large"|"xlarge";

const canons = [
 {n:1055,title:"Nozione e proprietà del matrimonio",text:"Il patto matrimoniale, con cui l'uomo e la donna stabiliscono tra loro la comunità di tutta la vita, per sua natura ordinata al bene dei coniugi e alla procreazione ed educazione della prole, tra battezzati è stato elevato da Cristo Signore alla dignità di sacramento."},
 {n:1063,title:"Cura pastorale e preparazione",text:"I pastori d'anime sono tenuti all'obbligo di provvedere che la propria comunità ecclesiastica presti ai fedeli quell'assistenza mediante la quale lo stato matrimoniale perseveri nello spirito cristiano e progredisca nella perfezione."},
 {n:1067,title:"Esame dei nubendi",text:"La Conferenza Episcopale stabilisca le norme circa l'esame dei nubendi, nonché circa le pubblicazioni matrimoniali e gli altri mezzi opportuni per compiere le necessarie investigazioni prematrimoniali."},
 {n:1083,title:"Età per contrarre matrimonio",text:"§ 1. L'uomo prima dei sedici anni compiuti, la donna prima dei quattordici pure compiuti, non possono celebrare un valido matrimonio.\n\n§ 2. È diritto della Conferenza Episcopale fissare una età maggiore per la lecita celebrazione del matrimonio."},
 {n:1095,title:"Incapacità a contrarre matrimonio",text:"Sono incapaci a contrarre matrimonio coloro che mancano di sufficiente uso di ragione, difettano gravemente di discrezione di giudizio o non possono assumere gli obblighi essenziali del matrimonio per cause di natura psichica."}
];
const sources=[
 {kind:"CEI · Delibera",title:"Delibera CEI n. 10",date:"23 dicembre 1983",relation:"determina",detail:"Età per la lecita celebrazione del matrimonio in Italia.",status:"Vigente"},
 {kind:"CEI · Decreto generale",title:"Decreto generale sul matrimonio canonico",date:"5 novembre 1990",relation:"sviluppa",detail:"Norme per l'applicazione del Titolo VII del Libro IV.",status:"Vigente"},
 {kind:"CIC · Concordanza",title:"Can. 1067",date:"CIC 1983",relation:"collega",detail:"Esame dei nubendi e investigazioni prematrimoniali.",status:"CIC"}
];
const searchIndex:SearchItem[]=[
 ...canons.map(c=>({id:`canon-${c.n}`,type:"Canone" as const,title:`Can. ${c.n}`,subtitle:c.title,text:c.text,terms:[String(c.n),`can ${c.n}`,c.title,c.text,"matrimonio"],canon:c.n,status:"CIC"})),
 {id:"cei-10",type:"Fonte italiana",title:"Delibera CEI n. 10",subtitle:"23 dicembre 1983 · Italia",text:"Età per la lecita celebrazione del matrimonio.",terms:["delibera 10","cei","eta matrimonio","nubendi","18 anni"],canon:1083,status:"Vigente"},
 {id:"dgm",type:"Fonte italiana",title:"Decreto generale sul matrimonio canonico",subtitle:"CEI · 5 novembre 1990",text:"Disciplina particolare del matrimonio canonico in Italia.",terms:["decreto matrimonio","matrimonio canonico","cei"],canon:1083,status:"Vigente"},
 {id:"materia",type:"Materia",title:"Matrimonio",subtitle:"Materia · rete normativa",text:"Canoni, fonti universali, normativa CEI e documenti applicativi.",terms:["matrimonio","nozze","coniugi","nubendi","consenso","nullita"],status:"Materia"}
];
const concepts:Record<string,string[]>={matrimonio:["matrimonio","nozze","coniugi","nubendi"],eta:["eta","anni","minima","1083"],nullita:["nullita","incapacita","consenso","1095"],preparazione:["preparazione","pastorale","esame","1063","1067"]};
function normalize(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/§/g," par ").replace(/\b(canone|can\.)\b/g,"can").replace(/[^a-z0-9]+/g," ").trim()}
function distance(a:string,b:string){const r=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let p=r[0];r[0]=i;for(let j=1;j<=b.length;j++){const t=r[j];r[j]=Math.min(r[j]+1,r[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=t}}return r[b.length]}
function score(item:SearchItem,raw:string){const q=normalize(raw);if(!q)return 0;const h=normalize([item.title,item.subtitle,item.text,...item.terms].join(" "));if(item.canon&&q===String(item.canon))return 1000;if(h.includes(q))return 700;let s=0;for(const w of q.split(" ")){if(w.length<2)continue;const hw=h.split(" ");if(hw.some(x=>x.startsWith(w)))s+=130;else if(w.length>=4&&hw.some(x=>Math.abs(x.length-w.length)<=2&&distance(x,w)<=2))s+=95;for(const terms of Object.values(concepts)){const n=terms.map(normalize);if(n.some(x=>x===w||(w.length>=4&&distance(x,w)<=2))&&n.some(x=>h.includes(x)))s+=70}}return s}
function Logo(){return <div className="logo"><span className="logo-symbol"><i>†</i><b>⌒</b></span><div><strong>Fonte Iuris</strong><small>Ius Canonicum · Italia</small></div></div>}

export default function Home(){
 const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [filter,setFilter]=useState("Tutti"); const [selected,setSelected]=useState(1083); const [theme,setTheme]=useState<Theme>("light"); const [fontSize,setFontSize]=useState<FontSize>("normal"); const [settings,setSettings]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.font=fontSize;localStorage.setItem("fi-theme",theme);localStorage.setItem("fi-font",fontSize)},[theme,fontSize]);
 useEffect(()=>{const t=localStorage.getItem("fi-theme") as Theme|null;const f=localStorage.getItem("fi-font") as FontSize|null;if(t)setTheme(t);if(f)setFontSize(f)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 const canon=canons.find(c=>c.n===selected)??canons[3];
 const results=useMemo(()=>searchIndex.map(item=>({item,score:score(item,query)})).filter(x=>x.score>0&&(filter==="Tutti"||x.item.type===filter)).sort((a,b)=>b.score-a.score).slice(0,8),[query,filter]);
 const filters=["Tutti","Canone","Fonte italiana","Materia"];
 const choose=(item:SearchItem)=>{if(item.canon)setSelected(item.canon);setOpen(false);setQuery("");setFilter("Tutti")};
 return <main className="app-shell">
  <aside className="nav-rail"><Logo/><p className="nav-label nav-label-first">Navigazione</p><nav><button className="active">▤ <span>Codice di Diritto Canonico</span></button><button>▧ <span>Fonti italiane</span></button><button>◇ <span>Materie</span></button><button>▱ <span>Documenti pastorali</span></button><button>⚖ <span>Giurisprudenza e prassi</span></button></nav><p className="nav-label">Strumenti</p><nav><button>↶ <span>Cronologia</span></button><button>☆ <span>Preferiti</span></button><button>✎ <span>Note personali</span></button><button>↗ <span>Concordanze</span></button><button>⌘ <span>Rete normativa</span></button></nav><div className="nav-footer"><span className="mini-mark">FI</span><p>Un’unica fonte,<br/>mille riferimenti.</p></div></aside>
  <section className="main-area">
   <header className="topbar"><div className="mobile-logo"><Logo/></div><div className="search-wrap"><span>⌕</span><input id="global-search" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} placeholder="Cerca canone, materia, fonte…" aria-label="Ricerca giuridica"/><button onClick={()=>setQuery("")} aria-label="Cancella">×</button>{open&&<div className="search-results"><div className="search-filters">{filters.map(f=><button key={f} className={filter===f?"selected":""} onMouseDown={e=>{e.preventDefault();setFilter(f)}}>{f}</button>)}</div>{!query?<><p className="result-label">Accesso rapido · scorciatoia ⌘K</p>{["matrimonio","1083","decreto matrimonio"].map(x=><button className="result" key={x} onMouseDown={()=>setQuery(x)}><b>{x}</b><small>Ricerca suggerita</small></button>)}</>:results.length?results.map(({item})=><button className="result" key={item.id} onMouseDown={()=>choose(item)}><span>{item.type}</span><b>{item.title} · {item.subtitle}</b><small>{item.text}</small></button>):<div className="empty"><b>Nessun vicolo cieco</b><p>Prova “matrimonio”, “1083”, “età minima” o “nullità”.</p></div>}</div>}</div><div className="top-actions"><button>↶</button><button>☆</button><button onClick={()=>setSettings(!settings)} aria-label="Accessibilità">Aa</button></div></header>
   {settings&&<aside className="settings-panel"><h3>Accessibilità</h3><p>Modalità</p><div className="segmented"><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}>☀ Chiaro</button><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}>☾ Scuro</button></div><p>Dimensione testo</p><div className="font-options"><button className={fontSize==="normal"?"selected":""} onClick={()=>setFontSize("normal")}><b>A</b> Normale</button><button className={fontSize==="large"?"selected":""} onClick={()=>setFontSize("large")}><b>A</b> Grande</button><button className={fontSize==="xlarge"?"selected":""} onClick={()=>setFontSize("xlarge")}><b>A</b> Molto grande</button></div></aside>}
   <div className="content-tabs"><button className="selected">Tutti</button><button>Canoni</button><button>Fonti italiane</button><button>Documenti</button><button>Materie</button><button>Giurisprudenza</button><span/><button>Filtri ◇</button></div>
   <div className="workspace"><section className="results-column"><p className="eyebrow">Titolo VII · Il matrimonio</p>{canons.map(c=><button key={c.n} className={`canon-card ${selected===c.n?"active":""}`} onClick={()=>setSelected(c.n)}><div><strong>Can. {c.n}</strong><b>{c.title}</b><p>{c.text.replace(/\n/g," ").slice(0,120)}…</p><small>CIC · Libro IV, Parte I, Tit. VII</small></div><span>☆</span></button>)}<article className="canon-card source-result"><strong>Delibera CEI n. 10 (23.12.1983)</strong><b>Età per la celebrazione del matrimonio</b><p>Normativa particolare italiana collegata al can. 1083 §2.</p><small>CEI · Delibere</small></article></section><article className="reader"><div className="canon-heading"><div><h1>Can. {canon.n}{canon.n===1083&&" §2"}</h1><h2>{canon.n===1083?"Età minima":canon.title}</h2></div><div><button>☆</button><button>↗</button><button>⋮</button></div></div><section className="canon-text">{canon.text.split("\n\n").map((p,i)=><p key={i}>{p}</p>)}</section><span className="path-pill">CIC · Libro IV, Parte I, Tit. VII</span><div className="reader-tabs"><button className="selected">Fonti collegate</button><button>Concordanze</button><button>Note</button><button>Storia della norma</button></div><section className="linked"><p className="eyebrow">Attuazione e normativa italiana</p>{sources.map(s=><article key={s.title}><span className="doc-icon">▤</span><div><strong>{s.title}</strong><p>{s.detail}</p></div><em>{s.relation}</em><b>›</b></article>)}</section></article><aside className="context-panel"><section><p className="eyebrow">Collocazione sistematica</p><b>Libro IV</b><span>La funzione di santificare della Chiesa</span><b>Parte I</b><span>I sacramenti</span><b>Titolo VII</b><span>Del matrimonio</span><strong>Can. {canon.n}</strong></section><section className="network"><p className="eyebrow">Rete normativa</p><div className="graph"><div className="node top">Delibera CEI n. 10<small>determina</small></div><div className="node left">Can. 1083 §1</div><div className="node center">Can. 1083 §2<small>Età minima</small></div><div className="node right">Decreto generale<small>sviluppa</small></div><div className="node bottom">Can. 1067<small>collega</small></div></div><button className="open-network">Apri rete completa →</button></section></aside></div>
  </section>
 </main>
}
