"use client";

import {useCallback, useEffect, useState} from "react";

type Theme="light"|"dark"; type FontSize="normal"|"large"|"xlarge";
type Unit={_id:string;unitType:string;number?:string;title:string;canonicalLabel?:string;canonicalId?:string;parent?:Unit|null};
type Version={_id:string;versionId:string;versionLabel:string;status:string;validFrom?:string;validUntil?:string;text:string;sourceCitation?:string;sourceUrl?:string;changeSummary?:string};
type Segment={_id:string;segmentId:string;segmentType:string;label:string;order:number;startOffset?:number;endOffset?:number;isFormalDivision?:boolean;parentId?:string};
type Canon={_id:string;number:number;canonicalId?:string;editorialTitle?:string;status:string;structure?:Unit|null;version?:Version|null;versions?:Version[];segments?:Segment[]};
type Nearby={_id:string;number:number;editorialTitle?:string;status:string;text?:Array<{children?:Array<{text?:string}>}>};
type SearchResult={_id:string;number:number;editorialTitle?:string;status:string};
type Book={_id:string;number?:string;title:string;canonicalLabel?:string;canonicalId:string};
type ReaderTab="sources"|"segments"|"history";

const FIRST_CANON=1; const LAST_CANON=1752;
function Logo(){return <div className="logo"><span className="logo-symbol"><i>†</i><b>⌒</b></span><div><strong>Fonte Iuris</strong><small>Ius Canonicum · Italia</small></div></div>}
function unitLabel(u:Unit){const names:Record<string,string>={book:"Libro",part:"Parte",section:"Sezione",title:"Titolo",chapter:"Capitolo",article:"Articolo"};return `${names[u.unitType]??u.unitType}${u.number?` ${u.number}`:""}`}
function pathOf(unit?:Unit|null){const path:Unit[]=[];let current=unit??null;while(current){path.unshift(current);current=current.parent??null}return path}
function nearbyText(item:Nearby){return (item.text??[]).flatMap(b=>b.children??[]).map(c=>c.text??"").join(" ").trim()}
function statusLabel(status?:string){return status==="amended"?"Modificato":status==="repealed"?"Abrogato":status==="historical"?"Storico":"Vigente"}

export default function Home(){
 const [canon,setCanon]=useState<Canon|null>(null); const [nearby,setNearby]=useState<Nearby[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [query,setQuery]=useState(""); const [searchOpen,setSearchOpen]=useState(false); const [results,setResults]=useState<SearchResult[]>([]);
 const [books,setBooks]=useState<Book[]>([]); const [bookCanons,setBookCanons]=useState<Nearby[]>([]); const [browseBooks,setBrowseBooks]=useState(false); const [activeBook,setActiveBook]=useState<Book|null>(null);
 const [readerTab,setReaderTab]=useState<ReaderTab>("sources");
 const [theme,setTheme]=useState<Theme>("light"); const [fontSize,setFontSize]=useState<FontSize>("normal"); const [settings,setSettings]=useState(false);

 const loadCanon=useCallback(async(number:number)=>{setLoading(true);setError("");try{const r=await fetch(`/api/cic?number=${number}`);if(!r.ok)throw new Error();const data=await r.json();setCanon(data.canon);setNearby(data.nearby??[]);setBrowseBooks(false);setActiveBook(null);setReaderTab("sources");window.history.replaceState(null,"",`?can=${number}`)}catch{setError("Non riesco a leggere il corpus CIC.")}finally{setLoading(false)}},[]);
 const loadBooks=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/cic?browse=books");if(!r.ok)throw new Error();const data=await r.json();setBooks(data.books??[]);setBrowseBooks(true);setActiveBook(null);setBookCanons([])}catch{setError("Non riesco a leggere la struttura del CIC.")}finally{setLoading(false)}},[]);
 const loadBook=useCallback(async(book:Book)=>{setLoading(true);setError("");try{const r=await fetch(`/api/cic?book=${encodeURIComponent(book.canonicalId)}`);if(!r.ok)throw new Error();const data=await r.json();setBookCanons(data.canons??[]);setActiveBook(book);setBrowseBooks(true)}catch{setError("Non riesco a leggere i canoni del Libro selezionato.")}finally{setLoading(false)}},[]);

 useEffect(()=>{const raw=new URLSearchParams(window.location.search).get("can");const n=raw?Number(raw):NaN;loadCanon(Number.isInteger(n)&&n>=FIRST_CANON&&n<=LAST_CANON?n:FIRST_CANON)},[loadCanon]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.font=fontSize;localStorage.setItem("fi-theme",theme);localStorage.setItem("fi-font",fontSize)},[theme,fontSize]);
 useEffect(()=>{const t=localStorage.getItem("fi-theme") as Theme|null;const f=localStorage.getItem("fi-font") as FontSize|null;if(t)setTheme(t);if(f)setFontSize(f)},[]);
 useEffect(()=>{
  const onKey=(e:KeyboardEvent)=>{
   if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus();return;}
   if(e.metaKey||e.ctrlKey||e.altKey||document.activeElement?.tagName==="INPUT")return;
   if(e.key==="ArrowLeft"&&canon?.number&&canon.number>FIRST_CANON)loadCanon(canon.number-1);
   if(e.key==="ArrowRight"&&canon?.number&&canon.number<LAST_CANON)loadCanon(canon.number+1);
  };
  window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);
 },[canon,loadCanon]);
 useEffect(()=>{if(!query.trim()){setResults([]);return}const timer=setTimeout(async()=>{try{const r=await fetch(`/api/cic?q=${encodeURIComponent(query)}`);const data=await r.json();setResults(data.results??[])}catch{setResults([])}},90);return()=>clearTimeout(timer)},[query]);

 const choose=(n:number)=>{setSearchOpen(false);setQuery("");loadCanon(n)}; const path=pathOf(canon?.structure);
 const currentList=browseBooks?(activeBook?bookCanons:[]):nearby;

 return <main className="app-shell">
  <aside className="nav-rail"><Logo/><p className="nav-label nav-label-first">Navigazione</p><nav><button className="active" onClick={loadBooks}>▤ <span>Codice di Diritto Canonico</span></button><button title="Prossimo modulo dati">▧ <span>Fonti italiane</span></button><button title="Prossimo modulo dati">◇ <span>Materie</span></button><button title="Prossimo modulo dati">▱ <span>Documenti pastorali</span></button><button title="Prossimo modulo dati">⚖ <span>Giurisprudenza e prassi</span></button></nav><p className="nav-label">Strumenti</p><nav><button title="Prossimo modulo">↶ <span>Cronologia</span></button><button title="Prossimo modulo">☆ <span>Preferiti</span></button><button title="Prossimo modulo">✎ <span>Note personali</span></button><button onClick={()=>setReaderTab("segments")}>↗ <span>Segmenti del canone</span></button><button title="Prossimo modulo">⌘ <span>Rete normativa</span></button></nav><div className="nav-footer"><span className="mini-mark">FI</span><p>Un’unica fonte,<br/>mille riferimenti.</p></div></aside>
  <section className="main-area">
   <header className="topbar"><div className="mobile-logo"><Logo/></div><div className="search-wrap"><span>⌕</span><input id="global-search" value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} placeholder="Cerca canone, testo, materia…" aria-label="Ricerca giuridica"/><button onClick={()=>setQuery("")} aria-label="Cancella">×</button>{searchOpen&&<div className="search-results">{!query?<><p className="result-label">Accesso rapido · scorciatoia ⌘K</p>{[1,1055,1083,1671].map(n=><button className="result" key={n} onMouseDown={()=>choose(n)}><span>Canone</span><b>Can. {n}</b><small>Apri direttamente dal corpus CIC</small></button>)}</>:results.length?results.map(item=><button className="result" key={item._id} onMouseDown={()=>choose(item.number)}><span>Canone</span><b>Can. {item.number}{item.editorialTitle?` · ${item.editorialTitle}`:""}</b><small>{statusLabel(item.status)} · Apri</small></button>):<div className="empty"><b>Nessun risultato diretto</b><p>Prova un numero di canone oppure una parola presente nel testo normativo.</p></div>}</div>}</div><div className="top-actions"><button title="Canone precedente" onClick={()=>canon&&canon.number>FIRST_CANON&&loadCanon(canon.number-1)}>‹</button><button title="Canone successivo" onClick={()=>canon&&canon.number<LAST_CANON&&loadCanon(canon.number+1)}>›</button><button onClick={()=>setSettings(!settings)} aria-label="Accessibilità">Aa</button></div></header>
   {settings&&<aside className="settings-panel"><h3>Accessibilità</h3><p>Modalità</p><div className="segmented"><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}>☀ Chiaro</button><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}>☾ Scuro</button></div><p>Dimensione testo</p><div className="font-options"><button className={fontSize==="normal"?"selected":""} onClick={()=>setFontSize("normal")}><b>A</b> Normale</button><button className={fontSize==="large"?"selected":""} onClick={()=>setFontSize("large")}><b>A</b> Grande</button><button className={fontSize==="xlarge"?"selected":""} onClick={()=>setFontSize("xlarge")}><b>A</b> Molto grande</button></div></aside>}
   <div className="content-tabs"><button className="selected" onClick={loadBooks}>CIC 1983</button><button title="Prossimo modulo dati">Fonti italiane</button><button title="Prossimo modulo dati">Documenti</button><button title="Prossimo modulo dati">Materie</button><button title="Prossimo modulo dati">Giurisprudenza</button><span/><button onClick={loadBooks}>Libri ▤</button></div>
   {error?<div className="empty"><b>{error}</b></div>:loading&&!canon?<div className="empty"><b>Caricamento del CIC…</b></div>:browseBooks?<div className="workspace">
    <section className="results-column"><p className="eyebrow">{activeBook?`${activeBook.number?`Libro ${activeBook.number} · `:""}${activeBook.title}`:"I sette Libri del CIC"}</p>{activeBook?<><button className="canon-card" onClick={()=>{setActiveBook(null);setBookCanons([])}}><div><strong>← Tutti i Libri</strong><p>Torna alla struttura generale del Codice</p></div></button>{currentList.map(c=><button key={c._id} className="canon-card" onClick={()=>loadCanon(c.number)}><div><strong>Can. {c.number}</strong><b>{c.editorialTitle||"Codice di Diritto Canonico"}</b><p>{nearbyText(c).slice(0,130)||"Testo normativo"}{nearbyText(c).length>130?"…":""}</p><small>{statusLabel(c.status)} · Apri</small></div><span>›</span></button>)}</>:books.map(b=><button key={b._id} className="canon-card" onClick={()=>loadBook(b)}><div><strong>{b.number?`Libro ${b.number}`:"Libro"}</strong><b>{b.title}</b><p>{b.canonicalLabel||"Struttura ufficiale del CIC 1983"}</p><small>Apri il Libro →</small></div><span>›</span></button>)}</section>
    <article className="reader"><div className="canon-heading"><div><h1>{activeBook?`Libro ${activeBook.number??""}`:"CIC 1983"}</h1><h2>{activeBook?.title||"Struttura del Codice"}</h2></div></div><section className="canon-text"><p>{activeBook?`Seleziona uno dei ${bookCanons.length} canoni del Libro per aprirne il testo vigente, la collocazione sistematica, i segmenti e la storia delle versioni.`:"Seleziona uno dei sette Libri per navigare il Codice secondo la sua struttura reale."}</p></section></article><aside className="context-panel"><section><p className="eyebrow">Navigazione</p><b>Codex Iuris Canonici</b><span>Codice di Diritto Canonico · 1983</span>{activeBook&&<><b>Libro {activeBook.number}</b><span>{activeBook.title}</span><strong>{bookCanons.length} canoni</strong></>}</section></aside>
   </div>:canon&&<div className="workspace">
    <section className="results-column"><p className="eyebrow">Navigazione reale · CIC 1983</p>{nearby.map(c=><button key={c._id} className={`canon-card ${canon.number===c.number?"active":""}`} onClick={()=>loadCanon(c.number)}><div><strong>Can. {c.number}</strong><b>{c.editorialTitle||"Codice di Diritto Canonico"}</b><p>{nearbyText(c).slice(0,145)||"Testo normativo"}{nearbyText(c).length>145?"…":""}</p><small>{statusLabel(c.status)} · Apri</small></div><span>›</span></button>)}</section>
    <article className="reader"><div className="canon-heading"><div><h1>Can. {canon.number}</h1><h2>{canon.editorialTitle||canon.structure?.title||"Codice di Diritto Canonico"}</h2></div><div><button title="Canone precedente" onClick={()=>canon.number>FIRST_CANON&&loadCanon(canon.number-1)}>←</button><button title="Canone successivo" onClick={()=>canon.number<LAST_CANON&&loadCanon(canon.number+1)}>→</button></div></div><section className="canon-text">{canon.version?.text?.split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)||<p>Testo italiano vigente non disponibile.</p>}</section><span className="path-pill">{path.map(unitLabel).join(" · ")}</span><div className="reader-tabs"><button className={readerTab==="sources"?"selected":""} onClick={()=>setReaderTab("sources")}>Fonte</button><button className={readerTab==="segments"?"selected":""} onClick={()=>setReaderTab("segments")}>Segmenti</button><button className={readerTab==="history"?"selected":""} onClick={()=>setReaderTab("history")}>Storia della norma</button></div><section className="linked">{readerTab==="sources"&&<><p className="eyebrow">Versione normativa</p><article><span className="doc-icon">▤</span><div><strong>{canon.version?.versionLabel||"Versione corrente"}</strong><p>{canon.version?.sourceCitation||"Codice di Diritto Canonico"}{canon.version?.validFrom?` · dal ${canon.version.validFrom}`:""}</p>{canon.version?.sourceUrl&&<p><a href={canon.version.sourceUrl} target="_blank" rel="noreferrer">Apri la fonte ufficiale ↗</a></p>}</div><em>{statusLabel(canon.status).toLowerCase()}</em></article></>}{readerTab==="segments"&&<><p className="eyebrow">Struttura interna del canone</p>{canon.segments?.length?canon.segments.map(s=><article key={s._id}><span className="doc-icon">§</span><div><strong>{s.label||s.segmentId}</strong><p>{s.segmentType} · ordine {s.order}{typeof s.startOffset==="number"&&typeof s.endOffset==="number"?` · caratteri ${s.startOffset}–${s.endOffset}`:""}</p></div></article>):<article><div><strong>Nessuna divisione formale registrata</strong><p>Il canone non presenta segmenti separati nel corpus.</p></div></article>}</>}{readerTab==="history"&&<><p className="eyebrow">Versioni registrate</p>{canon.versions?.map(v=><article key={v._id}><span className="doc-icon">↶</span><div><strong>{v.versionLabel}</strong><p>{v.validFrom?`Dal ${v.validFrom}`:"Data iniziale non registrata"}{v.validUntil?` al ${v.validUntil}`:""}</p>{v.changeSummary&&<p>{v.changeSummary}</p>}</div><em>{v.status}</em></article>)}</>}</section></article>
    <aside className="context-panel"><section><p className="eyebrow">Collocazione sistematica</p>{path.map(u=><div key={u._id}><b>{unitLabel(u)}</b><span>{u.title}</span></div>)}<strong>Can. {canon.number}</strong></section><section className="network"><p className="eyebrow">Navigazione normativa</p><div className="graph"><div className="node top">{path[0]?unitLabel(path[0]):"CIC"}<small>{path[0]?.title}</small></div><div className="node left" onClick={()=>canon.number>FIRST_CANON&&loadCanon(canon.number-1)}>Can. {Math.max(FIRST_CANON,canon.number-1)}</div><div className="node center">Can. {canon.number}<small>{statusLabel(canon.status).toLowerCase()}</small></div><div className="node right" onClick={()=>canon.number<LAST_CANON&&loadCanon(canon.number+1)}>Can. {Math.min(LAST_CANON,canon.number+1)}</div><div className="node bottom">{canon.structure?unitLabel(canon.structure):"Struttura"}<small>{canon.structure?.title}</small></div></div><button className="open-network" onClick={loadBooks}>Apri struttura del CIC →</button></section></aside>
   </div>}
  </section>
 </main>
}