"use client";

import {useCallback, useEffect, useState} from "react";

type Theme="light"|"dark"; type FontSize="normal"|"large"|"xlarge";
type Unit={_id:string;unitType:string;number?:string;title:string;canonicalLabel?:string;parent?:Unit|null};
type Version={_id:string;versionId:string;versionLabel:string;status:string;validFrom?:string;validUntil?:string;text:string;sourceCitation?:string;sourceUrl?:string;changeSummary?:string};
type Canon={_id:string;number:number;canonicalId?:string;editorialTitle?:string;status:string;structure?:Unit|null;version?:Version|null};
type Nearby={_id:string;number:number;editorialTitle?:string;status:string;text?:Array<{children?:Array<{text?:string}>}>};
type SearchResult={_id:string;number:number;editorialTitle?:string;status:string};

function Logo(){return <div className="logo"><span className="logo-symbol"><i>†</i><b>⌒</b></span><div><strong>Fonte Iuris</strong><small>Ius Canonicum · Italia</small></div></div>}
function unitLabel(u:Unit){const names:Record<string,string>={book:"Libro",part:"Parte",section:"Sezione",title:"Titolo",chapter:"Capitolo",article:"Articolo"};return `${names[u.unitType]??u.unitType}${u.number?` ${u.number}`:""}`}
function pathOf(unit?:Unit|null){const path:Unit[]=[];let current=unit??null;while(current){path.unshift(current);current=current.parent??null}return path}
function nearbyText(item:Nearby){return (item.text??[]).flatMap(b=>b.children??[]).map(c=>c.text??"").join(" ").trim()}

export default function Home(){
 const [canon,setCanon]=useState<Canon|null>(null); const [nearby,setNearby]=useState<Nearby[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [query,setQuery]=useState(""); const [searchOpen,setSearchOpen]=useState(false); const [results,setResults]=useState<SearchResult[]>([]);
 const [theme,setTheme]=useState<Theme>("light"); const [fontSize,setFontSize]=useState<FontSize>("normal"); const [settings,setSettings]=useState(false);
 const loadCanon=useCallback(async(number:number)=>{setLoading(true);setError("");try{const r=await fetch(`/api/cic?number=${number}`);if(!r.ok)throw new Error();const data=await r.json();setCanon(data.canon);setNearby(data.nearby??[])}catch{setError("Non riesco a leggere il corpus CIC da Sanity.")}finally{setLoading(false)}},[]);
 useEffect(()=>{loadCanon(1083)},[loadCanon]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.font=fontSize;localStorage.setItem("fi-theme",theme);localStorage.setItem("fi-font",fontSize)},[theme,fontSize]);
 useEffect(()=>{const t=localStorage.getItem("fi-theme") as Theme|null;const f=localStorage.getItem("fi-font") as FontSize|null;if(t)setTheme(t);if(f)setFontSize(f)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{if(!query.trim()){setResults([]);return}const timer=setTimeout(async()=>{try{const r=await fetch(`/api/cic?q=${encodeURIComponent(query)}`);const data=await r.json();setResults(data.results??[])}catch{setResults([])}},90);return()=>clearTimeout(timer)},[query]);
 const choose=(n:number)=>{setSearchOpen(false);setQuery("");loadCanon(n)}; const path=pathOf(canon?.structure);
 return <main className="app-shell">
  <aside className="nav-rail"><Logo/><p className="nav-label nav-label-first">Navigazione</p><nav><button className="active">▤ <span>Codice di Diritto Canonico</span></button><button>▧ <span>Fonti italiane</span></button><button>◇ <span>Materie</span></button><button>▱ <span>Documenti pastorali</span></button><button>⚖ <span>Giurisprudenza e prassi</span></button></nav><p className="nav-label">Strumenti</p><nav><button>↶ <span>Cronologia</span></button><button>☆ <span>Preferiti</span></button><button>✎ <span>Note personali</span></button><button>↗ <span>Concordanze</span></button><button>⌘ <span>Rete normativa</span></button></nav><div className="nav-footer"><span className="mini-mark">FI</span><p>Un’unica fonte,<br/>mille riferimenti.</p></div></aside>
  <section className="main-area">
   <header className="topbar"><div className="mobile-logo"><Logo/></div><div className="search-wrap"><span>⌕</span><input id="global-search" value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} placeholder="Cerca canone, materia, fonte…" aria-label="Ricerca giuridica"/><button onClick={()=>setQuery("")} aria-label="Cancella">×</button>{searchOpen&&<div className="search-results">{!query?<><p className="result-label">Accesso rapido · scorciatoia ⌘K</p>{[1055,1083,1095,1671].map(n=><button className="result" key={n} onMouseDown={()=>choose(n)}><span>Canone</span><b>Can. {n}</b><small>Apri direttamente dal corpus CIC</small></button>)}</>:results.length?results.map(item=><button className="result" key={item._id} onMouseDown={()=>choose(item.number)}><span>Canone</span><b>Can. {item.number}{item.editorialTitle?` · ${item.editorialTitle}`:""}</b><small>{item.status==="amended"?"Modificato":"Vigente"} · Sanity production</small></button>):<div className="empty"><b>Nessun vicolo cieco</b><p>Prova un numero di canone oppure un termine presente nei titoli e nelle parole chiave.</p></div>}</div>}</div><div className="top-actions"><button onClick={()=>canon&&canon.number>368&&loadCanon(canon.number-1)}>‹</button><button onClick={()=>canon&&canon.number<1752&&loadCanon(canon.number+1)}>›</button><button onClick={()=>setSettings(!settings)} aria-label="Accessibilità">Aa</button></div></header>
   {settings&&<aside className="settings-panel"><h3>Accessibilità</h3><p>Modalità</p><div className="segmented"><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}>☀ Chiaro</button><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}>☾ Scuro</button></div><p>Dimensione testo</p><div className="font-options"><button className={fontSize==="normal"?"selected":""} onClick={()=>setFontSize("normal")}><b>A</b> Normale</button><button className={fontSize==="large"?"selected":""} onClick={()=>setFontSize("large")}><b>A</b> Grande</button><button className={fontSize==="xlarge"?"selected":""} onClick={()=>setFontSize("xlarge")}><b>A</b> Molto grande</button></div></aside>}
   <div className="content-tabs"><button className="selected">CIC 1983</button><button>Fonti italiane</button><button>Documenti</button><button>Materie</button><button>Giurisprudenza</button><span/><button>Filtri ◇</button></div>
   {error?<div className="empty"><b>{error}</b></div>:loading&&!canon?<div className="empty"><b>Caricamento del CIC…</b></div>:canon&&<div className="workspace">
    <section className="results-column"><p className="eyebrow">Navigazione reale · CIC 1983</p>{nearby.map(c=><button key={c._id} className={`canon-card ${canon.number===c.number?"active":""}`} onClick={()=>loadCanon(c.number)}><div><strong>Can. {c.number}</strong><b>{c.editorialTitle||"Codice di Diritto Canonico"}</b><p>{nearbyText(c).slice(0,145) || "Testo normativo"}{nearbyText(c).length>145?"…":""}</p><small>{c.status==="amended"?"Modificato":"Vigente"} · Sanity</small></div><span>›</span></button>)}</section>
    <article className="reader"><div className="canon-heading"><div><h1>Can. {canon.number}</h1><h2>{canon.editorialTitle||canon.structure?.title||"Codice di Diritto Canonico"}</h2></div><div><button onClick={()=>canon.number>368&&loadCanon(canon.number-1)}>←</button><button onClick={()=>canon.number<1752&&loadCanon(canon.number+1)}>→</button></div></div><section className="canon-text">{canon.version?.text?.split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)||<p>Testo italiano vigente non disponibile.</p>}</section><span className="path-pill">{path.map(unitLabel).join(" · ")}</span><div className="reader-tabs"><button className="selected">Fonti collegate</button><button>Concordanze</button><button>Note</button><button>Storia della norma</button></div><section className="linked"><p className="eyebrow">Versione normativa</p><article><span className="doc-icon">▤</span><div><strong>{canon.version?.versionLabel||"Versione corrente"}</strong><p>{canon.version?.sourceCitation||"Codice di Diritto Canonico"}{canon.version?.validFrom?` · dal ${canon.version.validFrom}`:""}</p></div><em>{canon.status==="amended"?"modificato":"vigente"}</em><b>›</b></article></section></article>
    <aside className="context-panel"><section><p className="eyebrow">Collocazione sistematica</p>{path.map(u=><div key={u._id}><b>{unitLabel(u)}</b><span>{u.title}</span></div>)}<strong>Can. {canon.number}</strong></section><section className="network"><p className="eyebrow">Dati reali</p><div className="graph"><div className="node top">{path[0]?unitLabel(path[0]):"CIC"}<small>{path[0]?.title}</small></div><div className="node left">Can. {Math.max(368,canon.number-1)}</div><div className="node center">Can. {canon.number}<small>{canon.status==="amended"?"modificato":"vigente"}</small></div><div className="node right">Can. {Math.min(1752,canon.number+1)}</div><div className="node bottom">{canon.structure?unitLabel(canon.structure):"Struttura"}<small>{canon.structure?.title}</small></div></div><button className="open-network">Rete normativa in costruzione →</button></section></aside>
   </div>}
  </section>
 </main>
}
