import {defineField, defineType} from 'sanity'

export const jurisprudentialDecisionType = defineType({
  name: 'jurisprudentialDecision',
  title: 'Decisione giurisprudenziale',
  type: 'document',
  fields: [
    defineField({name:'decisionId',title:'Identificatore stabile',type:'string',validation:(Rule)=>Rule.required()}),
    defineField({name:'title',title:'Titolo editoriale',type:'string',validation:(Rule)=>Rule.required()}),
    defineField({name:'tribunal',title:'Tribunale / autorità decidente',type:'string',validation:(Rule)=>Rule.required()}),
    defineField({name:'tribunalLevel',title:'Livello',type:'string',options:{list:[
      {title:'Rota Romana',value:'romanRota'},
      {title:'Segnatura Apostolica',value:'apostolicSignatura'},
      {title:'Tribunale apostolico / dicasteriale',value:'apostolicOther'},
      {title:'Tribunale ecclesiastico italiano',value:'italianEcclesiastical'},
      {title:'Tribunale ecclesiastico particolare',value:'particularEcclesiastical'},
      {title:'Giurisdizione civile rilevante',value:'civilRelevant'},
      {title:'Altro',value:'other'},
    ]},validation:(Rule)=>Rule.required()}),
    defineField({name:'decisionType',title:'Tipo di decisione',type:'string',options:{list:[
      {title:'Sentenza',value:'sentence'},
      {title:'Decreto',value:'decree'},
      {title:'Decisione amministrativa',value:'administrativeDecision'},
      {title:'Provvedimento processuale',value:'proceduralOrder'},
      {title:'Altro',value:'other'},
    ]},validation:(Rule)=>Rule.required()}),
    defineField({name:'decisionDate',title:'Data della decisione',type:'date',validation:(Rule)=>Rule.required()}),
    defineField({name:'protocolNumber',title:'Protocollo / numero causa',type:'string'}),
    defineField({name:'officialCitation',title:'Citazione ufficiale',type:'string'}),
    defineField({name:'causeType',title:'Materia / tipo di causa',type:'string'}),
    defineField({name:'caseLabel',title:'Denominazione pubblica o anonimizzata della causa',type:'string'}),
    defineField({name:'ponens',title:'Ponens / relatore',type:'string'}),
    defineField({name:'panel',title:'Collegio',type:'array',of:[{type:'string'}]}),
    defineField({name:'language',title:'Lingua',type:'string',options:{list:[
      {title:'Latino',value:'la'},{title:'Italiano',value:'it'},{title:'Inglese',value:'en'},{title:'Francese',value:'fr'},{title:'Spagnolo',value:'es'},{title:'Altra',value:'other'},
    ]}}),
    defineField({name:'publicationStatus',title:'Stato della pubblicazione',type:'string',initialValue:'officialReference',options:{list:[
      {title:'Testo ufficiale integrale',value:'officialFull'},
      {title:'Estratto ufficiale',value:'officialExcerpt'},
      {title:'Solo riferimento ufficiale',value:'officialReference'},
      {title:'Edizione secondaria verificata',value:'verifiedSecondary'},
      {title:'Da verificare',value:'pending'},
    ]},validation:(Rule)=>Rule.required()}),
    defineField({name:'privacyStatus',title:'Stato privacy / anonimizzazione',type:'string',initialValue:'publicAnonymized',options:{list:[
      {title:'Pubblica e anonimizzata',value:'publicAnonymized'},
      {title:'Pubblica',value:'public'},
      {title:'Solo metadati',value:'metadataOnly'},
      {title:'Accesso limitato / non pubblicare il testo',value:'restricted'},
    ]},validation:(Rule)=>Rule.required()}),
    defineField({name:'sourceDocument',title:'Fonte documentale',type:'reference',to:[{type:'sourceDocument'}],validation:(Rule)=>Rule.required(),description:'Conserva il documento acquisito, URL, snapshot e hash. La decisione è un’entità giuridico-giurisprudenziale distinta.'}),
    defineField({name:'dubium',title:'Dubium / questione decisa',type:'text',rows:4}),
    defineField({name:'proceduralOutcome',title:'Esito processuale',type:'string'}),
    defineField({name:'dispositive',title:'Dispositivo',type:'text',rows:5}),
    defineField({name:'ratioSummary',title:'Sintesi della ratio decidendi',type:'text',rows:8,description:'Sintesi editoriale verificata; non sostituisce il testo della decisione.'}),
    defineField({name:'holdings',title:'Principi / proposizioni giurisprudenziali estratte',type:'array',of:[{type:'object',name:'jurisprudentialHolding',fields:[
      {name:'proposition',title:'Proposizione',type:'text',rows:4,validation:(Rule)=>Rule.required()},
      {name:'holdingType',title:'Funzione',type:'string',options:{list:[
        {title:'Interpretazione',value:'interpretation'},
        {title:'Applicazione',value:'application'},
        {title:'Criterio probatorio',value:'evidentiary'},
        {title:'Criterio processuale',value:'procedural'},
        {title:'Distinzione / precisazione',value:'distinction'},
      ]}},
      {name:'relatedCanons',title:'Canoni',type:'array',of:[{type:'reference',to:[{type:'canon'}]}]},
      {name:'relatedConcepts',title:'Materie',type:'array',of:[{type:'reference',to:[{type:'legalConcept'}]}]},
      {name:'editorialStatus',title:'Verifica editoriale',type:'string',initialValue:'pending',options:{list:[{title:'Da verificare',value:'pending'},{title:'Verificata',value:'verified'}]}},
    ]}]}),
    defineField({name:'relatedCanons',title:'Canoni richiamati o applicati',type:'array',of:[{type:'reference',to:[{type:'canon'}]}]}),
    defineField({name:'relatedConcepts',title:'Materie collegate',type:'array',of:[{type:'reference',to:[{type:'legalConcept'}]}]}),
    defineField({name:'keywords',title:'Parole chiave',type:'array',of:[{type:'string'}],options:{layout:'tags'}}),
    defineField({name:'jurisprudentialContext',title:'Contesto e peso giurisprudenziale',type:'text',rows:5,description:'Descrive con cautela il ruolo della decisione, senza trasformarla automaticamente in precedente vincolante o norma generale.'}),
    defineField({name:'sourceResearch',title:'Controllo delle fonti',type:'object',fields:[
      {name:'status',title:'Stato verifica',type:'string',initialValue:'pending',options:{list:[
        {title:'Da verificare',value:'pending'},
        {title:'Fonte ufficiale verificata',value:'official-verified'},
        {title:'Scheda giurisprudenziale verificata',value:'juridical-verified'},
      ]}},
      {name:'checkedAt',title:'Verificato il',type:'datetime'},
      {name:'note',title:'Nota',type:'text',rows:3},
    ]}),
    defineField({name:'notes',title:'Note redazionali',type:'array',of:[{type:'block'}]}),
  ],
  orderings:[{title:'Data decisione',name:'decisionDateDesc',by:[{field:'decisionDate',direction:'desc'}]}],
  preview:{select:{title:'title',tribunal:'tribunal',decisionDate:'decisionDate'},prepare({title,tribunal,decisionDate}){return {title,subtitle:`${tribunal ?? ''} · ${decisionDate ?? ''}`}}},
})