import {defineField, defineType} from 'sanity'

export const jurisprudentialDecisionType = defineType({
 name:'jurisprudentialDecision',title:'Decisione giurisprudenziale',type:'document',fields:[
  defineField({name:'decisionId',title:'Identificatore stabile',type:'string',validation:r=>r.required()}),defineField({name:'title',title:'Titolo editoriale',type:'string',validation:r=>r.required()}),defineField({name:'tribunal',title:'Tribunale / autorità decidente',type:'string',validation:r=>r.required()}),
  defineField({name:'tribunalLevel',title:'Livello',type:'string',options:{list:[{title:'Rota Romana',value:'romanRota'},{title:'Segnatura Apostolica',value:'apostolicSignatura'},{title:'Tribunale apostolico / dicasteriale',value:'apostolicOther'},{title:'Tribunale ecclesiastico italiano',value:'italianEcclesiastical'},{title:'Tribunale ecclesiastico particolare',value:'particularEcclesiastical'},{title:'Giurisdizione civile rilevante',value:'civilRelevant'},{title:'Altro',value:'other'}]},validation:r=>r.required()}),
  defineField({name:'decisionType',title:'Tipo di decisione',type:'string',options:{list:[{title:'Sentenza',value:'sentence'},{title:'Decreto',value:'decree'},{title:'Decisione amministrativa',value:'administrativeDecision'},{title:'Provvedimento processuale',value:'proceduralOrder'},{title:'Altro',value:'other'}]},validation:r=>r.required()}),
  defineField({name:'decisionDate',title:'Data della decisione',type:'date',validation:r=>r.required()}),defineField({name:'protocolNumber',title:'Protocollo / numero causa',type:'string'}),defineField({name:'officialCitation',title:'Citazione ufficiale',type:'string'}),defineField({name:'causeType',title:'Materia / tipo di causa',type:'string'}),defineField({name:'caseLabel',title:'Denominazione pubblica o anonimizzata della causa',type:'string'}),
  defineField({name:'instanceLevel',title:'Grado di giudizio',type:'string',options:{list:[{title:'Prima istanza',value:'first'},{title:'Seconda istanza',value:'second'},{title:'Terza istanza',value:'third'},{title:'Ulteriore istanza',value:'further'},{title:'Non determinato',value:'unknown'}]},description:'Particolarmente rilevante per la Rota Romana, che giudica ordinariamente in appello e anche in terza o ulteriore istanza.'}),
  defineField({name:'ponens',title:'Ponens / relatore',type:'string'}),defineField({name:'panel',title:'Turnus / collegio giudicante',type:'array',of:[{type:'string'}]}),
  defineField({name:'rotalGrounds',title:'Capita / motivi della causa rotale',type:'array',of:[{type:'object',name:'rotalGround',fields:[{name:'label',title:'Caput / motivo',type:'string',validation:r=>r.required()},{name:'canon',title:'Canone principale',type:'reference',to:[{type:'canon'}]},{name:'party',title:'Parte cui il caput si riferisce',type:'string',options:{list:[{title:'Parte attrice',value:'petitioner'},{title:'Parte convenuta',value:'respondent'},{title:'Entrambe / non specificato',value:'bothOrUnspecified'}]}},{name:'outcome',title:'Esito sul caput',type:'string',options:{list:[{title:'Affermativo',value:'affirmative'},{title:'Negativo',value:'negative'},{title:'Non definito / non disponibile',value:'undetermined'}]}}]}],description:'Non ridurre una causa matrimoniale a un solo canone: conserva separatamente ciascun caput nullitatis e il relativo esito, quando attestato dalla decisione.'}),
  defineField({name:'language',title:'Lingua',type:'string',options:{list:[{title:'Latino',value:'la'},{title:'Italiano',value:'it'},{title:'Inglese',value:'en'},{title:'Francese',value:'fr'},{title:'Spagnolo',value:'es'},{title:'Altra',value:'other'}]}}),
  defineField({name:'publicationStatus',title:'Stato della pubblicazione',type:'string',initialValue:'officialReference',options:{list:[{title:'Testo ufficiale integrale',value:'officialFull'},{title:'Estratto ufficiale',value:'officialExcerpt'},{title:'Solo riferimento ufficiale',value:'officialReference'},{title:'Edizione secondaria verificata',value:'verifiedSecondary'},{title:'Da verificare',value:'pending'}]},validation:r=>r.required()}),
  defineField({name:'rotalPublication',title:'Pubblicazione nelle Decisiones seu Sententiae',type:'object',fields:[{name:'year',title:'Anno delle decisioni',type:'number'},{name:'volumeRoman',title:'Volume (numero romano)',type:'string'},{name:'volumeArabic',title:'Volume (numero arabo)',type:'number'},{name:'pages',title:'Pagine',type:'string'},{name:'isbn',title:'ISBN del volume',type:'string'}],description:'Identifica il contenitore ufficiale pubblicato dalla Rota/LEV; resta distinto dalla singola decisione.'}),
  defineField({name:'publicationReferences',title:'Pubblicazioni e apparato scientifico',type:'array',of:[{type:'object',fields:[{name:'kind',title:'Tipo',type:'string',options:{list:[{title:'Pubblicazione della decisione',value:'decision'},{title:'Traduzione',value:'translation'},{title:'Commento / nota',value:'commentary'}]}},{name:'citation',title:'Riferimento bibliografico',type:'string',validation:r=>r.required()},{name:'language',title:'Lingua',type:'string'}]}]}),
  defineField({name:'privacyStatus',title:'Stato privacy / anonimizzazione',type:'string',initialValue:'publicAnonymized',options:{list:[{title:'Pubblica e anonimizzata',value:'publicAnonymized'},{title:'Pubblica',value:'public'},{title:'Solo metadati',value:'metadataOnly'},{title:'Accesso limitato / non pubblicare il testo',value:'restricted'}]},validation:r=>r.required()}),
  defineField({name:'sourceDocument',title:'Fonte documentale',type:'reference',to:[{type:'sourceDocument'}],validation:r=>r.required(),description:'Conserva documento, URL, snapshot e hash; la decisione resta entità giurisprudenziale distinta.'}),
  defineField({name:'officialRepertorySummary',title:'Sintesi del repertorio ufficiale',type:'text',rows:5}),defineField({name:'dubium',title:'Dubium / formula del dubbio',type:'text',rows:4}),defineField({name:'proceduralOutcome',title:'Esito processuale complessivo',type:'string'}),defineField({name:'dispositive',title:'Dispositivo',type:'text',rows:5}),defineField({name:'ratioSummary',title:'Sintesi della ratio decidendi',type:'text',rows:8,description:'Sintesi editoriale verificata; non sostituisce il testo della decisione.'}),
  defineField({name:'holdings',title:'Principi / proposizioni giurisprudenziali estratte',type:'array',of:[{type:'object',name:'jurisprudentialHolding',fields:[{name:'proposition',title:'Proposizione',type:'text',rows:4,validation:r=>r.required()},{name:'holdingType',title:'Funzione',type:'string',options:{list:[{title:'Interpretazione',value:'interpretation'},{title:'Applicazione',value:'application'},{title:'Criterio probatorio',value:'evidentiary'},{title:'Criterio processuale',value:'procedural'},{title:'Distinzione / precisazione',value:'distinction'}]}},{name:'basis',title:'Base documentaria',type:'string',options:{list:[{title:'Testo integrale ufficiale',value:'officialFullText'},{title:'Repertorio ufficiale',value:'officialRepertory'},{title:'Edizione ufficiale Decisiones',value:'officialRotalEdition'}]},validation:r=>r.required()},{name:'paragraphOrPage',title:'Localizzazione nel testo',type:'string',description:'Numero/i della decisione o pagina/e dell’edizione ufficiale che sostengono la proposizione.'},{name:'relatedCanons',title:'Canoni',type:'array',of:[{type:'reference',to:[{type:'canon'}]}]},{name:'relatedConcepts',title:'Materie',type:'array',of:[{type:'reference',to:[{type:'legalConcept'}]}]},{name:'editorialStatus',title:'Verifica editoriale',type:'string',initialValue:'pending',options:{list:[{title:'Da verificare',value:'pending'},{title:'Verificata',value:'verified'}]}}]}]}),
  defineField({name:'relatedCanons',title:'Canoni richiamati o applicati',type:'array',of:[{type:'reference',to:[{type:'canon'}]}]}),defineField({name:'relatedConcepts',title:'Materie collegate',type:'array',of:[{type:'reference',to:[{type:'legalConcept'}]}]}),defineField({name:'keywords',title:'Parole chiave',type:'array',of:[{type:'string'}],options:{layout:'tags'}}),defineField({name:'jurisprudentialContext',title:'Contesto e peso giurisprudenziale',type:'text',rows:5}),
  defineField({name:'sourceResearch',title:'Controllo delle fonti',type:'object',fields:[{name:'status',title:'Stato verifica',type:'string',initialValue:'pending',options:{list:[{title:'Da verificare',value:'pending'},{title:'Fonte ufficiale verificata',value:'official-verified'},{title:'Scheda giurisprudenziale verificata',value:'juridical-verified'}]}},{name:'checkedAt',title:'Verificato il',type:'datetime'},{name:'note',title:'Nota',type:'text',rows:3}]}),defineField({name:'notes',title:'Note redazionali',type:'array',of:[{type:'block'}]})
 ],orderings:[{title:'Data decisione',name:'decisionDateDesc',by:[{field:'decisionDate',direction:'desc'}]}],preview:{select:{title:'title',tribunal:'tribunal',decisionDate:'decisionDate'},prepare({title,tribunal,decisionDate}){return {title,subtitle:`${tribunal??''} · ${decisionDate??''}`}}}
})