import Link from "next/link";
import {notFound} from "next/navigation";
import LegalCorpusShell from "../../LegalCorpusShell";
import styles from "./materia-detail.module.css";

const PROJECT_ID="2rq93txn",DATASET="production",API_VERSION="2026-03-25";
type Ref={_id:string;label?:string;title?:string;number?:number;slug?:{current:string}};
type Bib={citation:string;kind?:string;url?:string;note?:string};
type Materia={_id:string;label:string;slug:{current:string};definition:string;academicSummary?:string;systematicFramework?:unknown;ecclesiologicalFoundation?:unknown;codicialDiscipline?:unknown;normativeEvolution?:unknown;extraCodicialLegislation?:unknown;interpretationDoctrine?:unknown;interpretation?:unknown;jurisprudencePractice?:unknown;controversialIssues?:unknown;bibliography?:Bib[];synonyms?:string[];broaderConcept?:Ref;children?:Materia[];relatedCanons?:Ref[];relatedSources?:Ref[];relatedProvisions?:Ref[];relatedConcepts?:Ref[]};
function text(v:unknown){if(typeof v==="string")return v;if(!Array.isArray(v))return "";return v.map((b:any)=>b?.children?.map((c:any)=>c?.text??"").join("")??"").filter(Boolean).join("\n\n")}
async function load(slug:string):Promise<Materia|null>{const q=`*[_type=="legalConcept"&&slug.current==$slug][0]{...,"broaderConcept":broaderConcept->{_id,label,slug},"children":*[_type=="legalConcept"&&broaderConcept._ref==^._id]|order(label asc){_id,label,slug,definition,systematicFramework},"relatedCanons":relatedCanons[]->{_id,number,editorialTitle},"relatedSources":relatedSources[]->{_id,title},"relatedProvisions":relatedProvisions[]->{_id,title},"relatedConcepts":relatedConcepts[]->{_id,label,slug}}`;const u=new URL(`https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/query/${DATASET}`);u.searchParams.set("query",q);u.searchParams.set("$slug",JSON.stringify(slug));const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error("Materia non disponibile");return (await r.json()).result??null}
const sections=[
 ["quadro","Inquadramento giuridico e sistematico","systematicFramework"],
 ["fondamento","Fondamento ecclesiologico e conciliare","ecclesiologicalFoundation"],
 ["disciplina","Disciplina codiciale","codicialDiscipline"],
 ["evoluzione","Evoluzione normativa","normativeEvolution"],
 ["extracodiciale","Legislazione extracodiciale","extraCodicialLegislation"],
 ["interpretazione","Interpretazione e dottrina","interpretation"],
 ["giurisprudenza","Giurisprudenza e prassi","jurisprudencePractice"],
 ["questioni","Questioni problematiche e controverse","controversialIssues"]
] as const;
export default async function MateriaDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const m=await load(slug);if(!m)notFound();const content=(key:string)=>key==="interpretation"?text(m.interpretation)||text(m.interpretationDoctrine):text((m as any)[key]);const visible=sections.filter(([, ,k])=>content(k));return <LegalCorpusShell section="Dossier accademico" activeSection="materie"><main className={styles.page}>
 <div className={styles.breadcrumb}><Link href="/materie">Materie</Link><span>›</span><span>{m.label}</span></div>
 <header className={styles.hero}><p className={styles.eyebrow}>Materia · dossier giuridico</p><h1 className={styles.title}>{m.label}</h1><p className={styles.definition}>{m.academicSummary||m.definition}</p><div className={styles.chips}>{m.broaderConcept?.label?<span className={styles.chip}>Collocazione sistematica · {m.broaderConcept.label}</span>:null}{m.synonyms?.slice(0,3).map(s=><span className={styles.chip} key={s}>{s}</span>)}{m.relatedCanons?.length?<span className={styles.chip}>{m.relatedCanons.length} canoni collegati</span>:null}<span className={styles.chip}>Livello accademico</span></div></header>
 <div className={styles.grid}><aside className={styles.toc}><div className={styles.tocBox}><h2 className={styles.tocTitle}>Indice del dossier</h2>{m.children?.length?<a href="#mappa">Mappa della materia</a>:null}{visible.map(([id,title])=><a href={`#${id}`} key={id}>{title}</a>)}{m.bibliography?.length?<a href="#bibliografia">Bibliografia</a>:null}</div></aside>
 <article className={styles.main}>{m.children?.length?<section id="mappa" className={styles.section}><h2>Mappa della materia</h2><p>Articolazione sistematica del dossier. Ogni nucleo apre una scheda autonoma mantenendo il rapporto con la materia principale.</p><div className={styles.map}>{m.children.map(c=><Link className={styles.mapCard} href={`/materie/${c.slug.current}`} key={c._id}><strong>{c.label}</strong><span>{c.definition}</span></Link>)}</div></section>:null}{visible.map(([id,title,key])=><section id={id} className={styles.section} key={id}><h2>{title}</h2>{content(key).split("\n\n").map((p,i)=><p key={i}>{p}</p>)}</section>)}{m.bibliography?.length?<section id="bibliografia" className={styles.section}><h2>Bibliografia scientifica</h2><ol className={styles.bibliography}>{m.bibliography.map((b,i)=><li key={i}>{b.citation}{b.note?` — ${b.note}`:""}</li>)}</ol></section>:null}</article>
 <aside className={styles.rail}><div className={styles.railBox}><h2 className={styles.railTitle}>Rete normativa</h2>{m.relatedCanons?.length?m.relatedCanons.map(c=><div className={styles.railItem} key={c._id}><Link href={`/?can=${c.number}`}>Can. {c.number}</Link></div>):<div className={styles.railItem}>I riferimenti specifici sono descritti nel dossier.</div>}</div><div className={styles.railBox}><h2 className={styles.railTitle}>Fonti collegate</h2>{m.relatedSources?.map(s=><div className={styles.railItem} key={s._id}><Link href={`/legal/${s._id}`}>{s.title}</Link></div>)}{m.relatedProvisions?.map(s=><div className={styles.railItem} key={s._id}><Link href={`/legal/${s._id}`}>{s.title}</Link></div>)}{!m.relatedSources?.length&&!m.relatedProvisions?.length?<div className={styles.railItem}>Le fonti sono richiamate nelle sezioni scientifiche.</div>:null}</div><Link className={styles.back} href="/materie">← Tutte le materie</Link></aside></div>
 </main></LegalCorpusShell>}
