"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
type CanonRef={_id:string;number:number;editorialTitle?:string};
type Parent={_id:string;label:string;slug?:{current:string};broaderConcept?:Parent|null};
type Concept={_id:string;label:string;slug?:{current:string};definition:string;synonyms?:string[];broaderConcept?:Parent|null;relatedCanons?:CanonRef[]};
function path(c:Concept){const p=[] as string[];if(c.broaderConcept?.broaderConcept?.label)p.push(c.broaderConcept.broaderConcept.label);if(c.broaderConcept?.label)p.push(c.broaderConcept.label);return p}
export default function MaterieBrowser({concepts}:{concepts:Concept[]}){
 const [query,setQuery]=useState("");const q=query.trim().toLocaleLowerCase("it");
 const roots=useMemo(()=>concepts.filter(c=>!c.broaderConcept),[concepts]);
 const children=(id:string)=>concepts.filter(c=>c.broaderConcept?._id===id);
 const results=useMemo(()=>q?concepts.filter(c=>[c.label,c.definition,...(c.synonyms??[]),...path(c),...(c.relatedCanons??[]).map(x=>`canone ${x.number} ${x.editorialTitle??""}`)].join(" ").toLocaleLowerCase("it").includes(q)):[],[concepts,q]);
 return <div style={{maxWidth:1280,margin:"0 auto",padding:"34px 28px 60px"}}>
  <p style={{margin:0,color:"var(--gold)",fontWeight:850,textTransform:"uppercase",fontSize:12}}>Materie</p><h1 style={{fontFamily:"Georgia,serif",color:"var(--blue)",fontSize:"2.3rem",margin:"8px 0"}}>Mappa delle materie canonistiche</h1><p style={{maxWidth:850,color:"var(--muted)",lineHeight:1.65,margin:"0 0 25px"}}>Accedi al diritto canonico attraverso le sue grandi aree sistematiche oppure cerca direttamente una materia o un nucleo tematico.</p>
  <div style={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:12,padding:16,marginBottom:26}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca, ad esempio: matrimonio, consenso, processo, sanzioni…" aria-label="Cerca nelle materie" style={{width:"100%",boxSizing:"border-box",padding:"13px 14px",border:"1px solid var(--line)",borderRadius:8,background:"var(--surface2)",color:"var(--ink)",font:"inherit"}}/></div>
  {q?<section><p style={{fontSize:12,color:"var(--muted)",margin:"0 0 12px"}}>{results.length} risultati per <strong>“{query.trim()}”</strong></p><div style={{display:"grid",gap:10}}>{results.map(c=><article key={c._id} style={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:11,padding:"17px 20px"}}><div style={{fontSize:10,textTransform:"uppercase",letterSpacing:".04em",color:"var(--gold)",fontWeight:800,marginBottom:6px}}>{path(c).length?path(c).join(" › "):"Area canonistica"}</div><div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start"}}><div><h2 style={{font:"700 1.15rem Georgia,serif",color:"var(--blue)",margin:"0 0 7px"}}>{c.label}</h2><p style={{fontSize:12,lineHeight:1.55,margin:0,maxWidth:850}}>{c.definition}</p></div>{c.slug?.current&&<Link href={`/materie/${c.slug.current}`} style={{whiteSpace:"nowrap",textDecoration:"none",fontSize:11,fontWeight:850,color:"var(--blue)"}}>Apri dossier →</Link>}</div></article>)}</div>{!results.length&&<div style={{padding:22,background:"var(--surface)",border:"1px solid var(--line)",borderRadius:11}}>Nessuna materia corrisponde alla ricerca.</div>}</section>:
  <section><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(340px,1fr))",gap:15}}>{roots.map(area=>{const level2=children(area._id);return <article key={area._id} style={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:13,padding:22,boxShadow:"0 2px 8px rgba(10,30,50,.03)"}}><p style={{margin:"0 0 6px",fontSize:10,fontWeight:850,color:"var(--gold)",textTransform:"uppercase",letterSpacing:".05em"}}>Area canonistica</p><h2 style={{font:"700 1.25rem Georgia,serif",color:"var(--blue)",margin:"0 0 8px"}}>{area.slug?.current?<Link href={`/materie/${area.slug.current}`} style={{color:"inherit",textDecoration:"none"}}>{area.label}</Link>:area.label}</h2><p style={{fontSize:12,lineHeight:1.55,color:"var(--muted)",margin:"0 0 15px"}}>{area.definition}</p>{level2.length>0&&<div style={{borderTop:"1px solid var(--line)",paddingTop:11}}>{level2.map(m=><div key={m._id} style={{padding:"8px 0",borderBottom:"1px solid var(--line)"}}><Link href={`/materie/${m.slug?.current}`} style={{fontSize:12,fontWeight:800,color:"var(--blue)",textDecoration:"none"}}>{m.label}</Link>{children(m._id).length>0&&<div style={{fontSize:10,color:"var(--muted)",marginTop:4px}}>{children(m._id).slice(0,5).map(x=>x.label).join(" · ")}{children(m._id).length>5?" · …":""}</div>}</div>)}</div>}</article>})}</div></section>}
 </div>
}