import Link from "next/link";
import {notFound} from "next/navigation";
import LegalCorpusShell from "../../LegalCorpusShell";
import styles from "./legal-page.module.css";

const PROJECT_ID="2rq93txn";
const DATASET="production";
const API_VERSION="2026-03-25";

async function loadLegal(id:string){
  const query=`{"selected":*[_id==$id][0]{_id,_type,"sourceId":select(_type=="italianProvision"=>sourceDocument._ref,_id)},"source":*[_type=="sourceDocument" && _id==*[_id==$id][0].sourceDocument._ref][0]{_id},"directSource":*[_type=="sourceDocument" && _id==$id][0]{_id}}`;
  const base=new URL(`https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/query/${DATASET}`);base.searchParams.set("query",query);base.searchParams.set("$id",JSON.stringify(id));
  const first=await fetch(base,{cache:"no-store"});if(!first.ok)return null;const found=(await first.json()).result;const sourceId=found?.selected?.sourceId||found?.source?._id||found?.directSource?._id;if(!sourceId)return null;
  const mergedQuery=`*[_type=="sourceDocument" && _id==$sourceId][0]{_id,_type,title,shortTitle,issuer,status,effectiveFrom,effectiveUntil,officialCitation,officialUrl,sourceText,documentType,territorialScope,legalForce,"provision":*[_type=="italianProvision" && sourceDocument._ref==^._id][0]{_id,title,summary,"normativeText":pt::text(normativeText),provisionType,issuer,status,effectiveFrom,effectiveUntil,territorialScope,legalForce,legalVerification},"relations":*[_type=="legalRelation" && (sourceDocument._ref==^._id || source._ref==^._id || source._ref in *[_type=="italianProvision" && sourceDocument._ref==^._id]._id || target._ref==^._id)]{_id,relationType,note,officialCitation,verified,source->{_id,_type,title,editorialTitle,number,provisionId,documentId},target->{_id,_type,title,editorialTitle,number,provisionId,documentId}}}`;
  const url=new URL(`https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/query/${DATASET}`);url.searchParams.set("query",mergedQuery);url.searchParams.set("$sourceId",JSON.stringify(sourceId));
  const res=await fetch(url,{cache:"no-store"});if(!res.ok)return null;return (await res.json()).result;
}
function statusLabel(status?:string){return status==="inForce"?"Vigente":status==="amended"?"Modificato":status==="repealed"?"Abrogato":status==="historical"?"Storico":status||""}
function scopeLabel(scope?:string){return scope==="universal"?"Universale":scope==="italy"?"Italia":scope||""}
function forceLabel(force?:string){return force==="normative"?"Normativa":force||""}
function relationLabel(type?:string){const map:Record<string,string>={interprets:"Interpreta",implements:"Attua",determines:"Determina",specifies:"Specifica",integrates:"Integra",derogates:"Deroga",replaces:"Sostituisce",repeals:"Abroga",refersTo:"Rinvio",presupposes:"Presuppone",appliesInItaly:"Applicazione in Italia",regulatesProcedure:"Regola la procedura",amendsText:"Modifica il testo",concordance:"Concordanza",exception:"Eccezione"};return map[type??""]||type||"Relazione normativa"}
function decodeEntities(text:string){const entities:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",agrave:"à",egrave:"è",eacute:"é",igrave:"ì",ograve:"ò",ugrave:"ù",ccedil:"ç",ntilde:"ñ",ecirc:"ê",aacute:"á",iacute:"í",oacute:"ó",uacute:"ú",times:"×"};return text.replace(/&([a-z]+);/gi,(m,key)=>entities[key.toLowerCase()]??m).replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
function cleanOfficialText(raw?:string){if(!raw)return "";const junk=new Set(["la santa sede","italiano","italian","français","english","português","español","deutsch","polski","العربية","العربيّة","中文","latine","×","magisterium","calendario","celebrazioni liturgiche","biglietti udienze e celebrazioni pontificie","sommi pontefici","collegio cardinalizio","curia romana e altre organizzazioni","sinodo","sala stampa","vatican news - radio vaticana","l'osservatore romano","francesco","motu proprio","a","generazione pdf in corso.....","generazione pdf in corso...","de","en","es","fr","hr","it","la","pl","pt","zh_cn","zh_tw","-"]);const languageMenu=/^(?:-\s*)?(?:DE|EN|ES|FR|HR|IT|LA|PL|PT|ZH_CN|ZH_TW)(?:\s*-\s*(?:DE|EN|ES|FR|HR|IT|LA|PL|PT|ZH_CN|ZH_TW))*$/i;return decodeEntities(raw).split(/\r?\n/).map(line=>line.trimEnd()).filter(line=>{const trimmed=line.trim();const key=trimmed.toLocaleLowerCase("it");return !junk.has(key)&&!languageMenu.test(trimmed)}).join("\n").replace(/\n{3,}/g,"\n\n").trim();}

export default async function LegalPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const doc=await loadLegal(decodeURIComponent(id));if(!doc)notFound();const p=doc.provision;
 const title=p?.title||doc.title,issuer=p?.issuer||doc.issuer,status=p?.status||doc.status,effectiveFrom=p?.effectiveFrom||doc.effectiveFrom,effectiveUntil=p?.effectiveUntil||doc.effectiveUntil,scope=p?.territorialScope||doc.territorialScope,force=p?.legalForce||doc.legalForce;
 const text=cleanOfficialText(p?.normativeText||doc.sourceText);const relations=Array.from(new Map((doc.relations??[]).map((r:any)=>[r._id,r])).values()) as any[];const kind=(p?.provisionType||doc.documentType||"Atto normativo").replace(/([a-z])([A-Z])/g,"$1 $2");
 const canonRelations=relations.filter(r=>r.target?.number||r.source?.number);
 return <LegalCorpusShell section="Lettura interna"><div className={styles.page}>
  <div className={styles.breadcrumb}><Link href="/fonti">Fonti normative</Link><span>›</span><span>{title}</span></div>
  <div className={styles.layout}>
   <article className={styles.article}>
    <div className={styles.hero}><p className={styles.kind}>{kind}</p><h1 className={styles.title}>{title}</h1><div className={styles.meta}>{issuer&&<span className={styles.chip}>{issuer}</span>}{status&&<span className={`${styles.chip} ${styles.chipStrong}`}>{statusLabel(status)}</span>}{effectiveFrom&&<span className={styles.chip}>In vigore dal {effectiveFrom}</span>}{scope&&<span className={styles.chip}>{scopeLabel(scope)}</span>}</div></div>
    <nav className={styles.studyPath} aria-label="Percorso di lettura dell'atto"><p className={styles.studyIntro}>Percorso di lettura</p><div className={styles.studySteps}><a href="#identifica"><b>01</b><span>Identifica l’atto<small>natura, autorità, efficacia</small></span></a>{p?.summary&&<a href="#comprendi"><b>02</b><span>Comprendi cosa dispone<small>sintesi giuridica</small></span></a>}<a href="#testo"><b>{p?.summary?"03":"02"}</b><span>Leggi il testo<small>testo acquisito nel corpus</small></span></a>{relations.length>0&&<a href="#relazioni"><b>{p?.summary?"04":"03"}</b><span>Vedi cosa cambia<small>canoni e relazioni normative</small></span></a>}<a href="#provenienza"><b>{p?.summary?(relations.length?"05":"04"):(relations.length?"04":"03")}</b><span>Verifica la fonte<small>provenienza documentale</small></span></a></div></nav>
    <div className={styles.body}><section id="identifica" className={styles.readSection}><h2>Identificazione giuridica</h2><div className={styles.identityGrid}>{issuer&&<div><b>Autorità</b><span>{issuer}</span></div>}<div><b>Natura</b><span>{kind}</span></div>{status&&<div><b>Stato</b><span>{statusLabel(status)}</span></div>}{effectiveFrom&&<div><b>Efficacia</b><span>dal {effectiveFrom}{effectiveUntil?` al ${effectiveUntil}`:""}</span></div>}{scope&&<div><b>Ambito</b><span>{scopeLabel(scope)}</span></div>}{doc.officialCitation&&<div><b>Citazione</b><span>{doc.officialCitation}</span></div>}</div></section>{p?.summary&&<section id="comprendi" className={`${styles.readSection} ${styles.summary}`}><h2>Che cosa dispone</h2><p>{p.summary}</p></section>}<section id="testo" className={styles.readSection}><h2>Testo ufficiale</h2>{text?<div className={styles.officialText}>{text}</div>:<p className={styles.empty}>Testo ufficiale non ancora acquisito nel corpus.</p>}</section></div>
   </article>
   <aside className={styles.aside}>
    <section className={styles.panel}><h3>Orientamento rapido</h3><div className={styles.fact}><b>Tipo di atto</b><span>{kind}</span></div>{force&&<div className={styles.fact}><b>Forza</b><span>{forceLabel(force)}</span></div>}{canonRelations.length>0&&<div className={styles.fact}><b>Incidenza codiciale</b><span>{canonRelations.length} {canonRelations.length===1?"relazione con un canone":"relazioni con canoni"}</span></div>}</section>
    {relations.length>0&&<section id="relazioni" className={styles.panel}><h3>Che cosa modifica o integra</h3><p className={styles.panelLead}>Qui Fonte Iuris ricostruisce i rapporti dell’atto con il Codice e con le altre fonti.</p>{relations.map((r:any)=><div key={r._id} className={styles.relation}><span className={styles.relationType}>{relationLabel(r.relationType)}</span><p>{r.target?.number?<>Can. <Link href={`/?can=${r.target.number}`}>{r.target.number}</Link></>:r.source?.number?<>Can. <Link href={`/?can=${r.source.number}`}>{r.source.number}</Link></>:r.note||r.officialCitation||"Relazione registrata"}</p></div>)}</section>}
    <section id="provenienza" className={styles.panel}><h3>Provenienza e verifica</h3><div className={styles.fact}><b>Corpus</b><span>Fonte Iuris · testo acquisito e consultabile internamente</span></div>{doc.officialUrl&&<a className={styles.sourceLink} href={doc.officialUrl} target="_blank" rel="noreferrer">Fonte ufficiale esterna ↗</a>}<Link href="/fonti" className={styles.returnLink}>← Torna alle fonti normative</Link></section>
   </aside>
  </div>
 </div></LegalCorpusShell>
}